AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deliberately vulnerable lab: public S3 secrets file + EC2 app that exposes a .env file and
  contains hardcoded secrets in UserData (for educational testing).

Parameters:
  StackName:
    Type: String
    Default: delete-me-hardcoded-secrets
    Description: Name prefix for resources (used in names)

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair name for SSH access

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where resources will be deployed

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet ID for EC2 instance

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: Latest Amazon Linux 2023 AMI (via SSM public parameter)
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

Resources:
  # ----------------------------
  # Public S3 bucket w/ secrets
  # ----------------------------
  SecretsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StackName}-secrets-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub "${StackName}-secrets-bucket"
        - Key: Purpose
          Value: SecurityTraining

  SecretsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecretsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicListBucket
            Effect: Allow
            Principal: "*"
            Action: s3:ListBucket
            Resource: !GetAtt SecretsBucket.Arn
          - Sid: PublicReadObjects
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub "${SecretsBucket.Arn}/*"

  # ----------------------------
  # Lambda to upload simple config file
  # ----------------------------
  ConfigFileLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${StackName}-config-file-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3PutObject
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub "${SecretsBucket.Arn}/*"

  CreateConfigFileFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${StackName}-create-config-file"
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt ConfigFileLambdaRole.Arn
      Timeout: 30
      Code:
        ZipFile: |
          import json
          import boto3
          import urllib.request

          def _send(event, context, status, data, physical_id=None):
              body = json.dumps({
                  "Status": status,
                  "Reason": "See CloudWatch Log Stream: " + context.log_stream_name,
                  "PhysicalResourceId": physical_id or context.log_stream_name,
                  "StackId": event["StackId"],
                  "RequestId": event["RequestId"],
                  "LogicalResourceId": event["LogicalResourceId"],
                  "Data": data or {}
              }).encode("utf-8")
              req = urllib.request.Request(
                  event["ResponseURL"],
                  data=body,
                  method="PUT",
                  headers={"Content-Type": "", "Content-Length": str(len(body))}
              )
              with urllib.request.urlopen(req) as _:
                  pass

          def handler(event, context):
              s3 = boto3.client("s3")
              bucket = event["ResourceProperties"]["Bucket"]
              key = event["ResourceProperties"]["Key"]

              if event["RequestType"] == "Delete":
                  _send(event, context, "SUCCESS", {"Key": key})
                  return

              # Simple config file format (like a configuration file)
              config_lines = [
                  '# ProjectX Production Configuration',
                  '# Database Settings',
                  'DB_HOST=prod-database.internal',
                  'DB_PORT=5432',
                  'DB_USER=admin',
                  'DB_PASSWORD=SuperSecretPassword123!',
                  '',
                  '# AWS Credentials',
                  'AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE',
                  'AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
                  '',
                  '# API Keys',
                  'API_KEY=sk_live_51HqSOF_example_main_api_key'
              ]
              config_content = '\n'.join(config_lines) + '\n'

              try:
                  s3.put_object(
                      Bucket=bucket,
                      Key=key,
                      Body=config_content,
                      ContentType="text/plain"
                  )
                  _send(event, context, "SUCCESS", {"Key": key}, physical_id=f"{bucket}/{key}")
              except Exception as e:
                  print("Error:", str(e))
                  _send(event, context, "FAILED", {"Error": str(e)})

  ConfigFileLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateConfigFileFunction
      Action: lambda:InvokeFunction
      Principal: cloudformation.amazonaws.com

  ConfigFile:
    Type: AWS::CloudFormation::CustomResource
    DependsOn:
      - SecretsBucketPolicy
      - CreateConfigFileFunction
      - ConfigFileLambdaPermission
    Properties:
      ServiceToken: !GetAtt CreateConfigFileFunction.Arn
      Bucket: !Ref SecretsBucket
      Key: config/app-config.json

  # ----------------------------
  # EC2 IAM + security group
  # ----------------------------
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${StackName}-ec2-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt SecretsBucket.Arn
                  - !Sub "${SecretsBucket.Arn}/*"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${StackName}-ec2-profile"
      Roles:
        - !Ref EC2InstanceRole

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${StackName}-ec2-sg"
      GroupDescription: Vulnerable web app SG (SSH + 8080)
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH (lab)
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
          Description: Web app (lab)
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # ----------------------------
  # EC2 instance (no UserData - setup script run manually by students)
  # ----------------------------
  VulnerableEC2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
      - ConfigFile
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t3.micro
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref EC2InstanceProfile
      MetadataOptions:
        HttpEndpoint: enabled
        HttpTokens: optional # VULNERABLE: IMDSv1 allowed
        HttpPutResponseHopLimit: 2
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref EC2SecurityGroup
Outputs:
  SecretsBucketName:
    Description: Name of the S3 bucket containing hardcoded secrets
    Value: !Ref SecretsBucket

  ConfigFileURL:
    Description: Public URL to the config file
    Value: !Sub "https://${SecretsBucket}.s3.${AWS::Region}.amazonaws.com/config/app-config.json"

  EC2PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt VulnerableEC2Instance.PublicIp

  AppURL:
    Description: URL to access the web application
    Value: !Sub "http://${VulnerableEC2Instance.PublicIp}:8080"
